### ISSUE TITLE
Provider crashes when limited access is given

### ISSUE THREAD

**Issue by kostyantyn** [nicoangelo/terraform-provider-personio#59]
First of all, thanks for working on this personio plugin! 

While testing it, I've created a token with the limited permissions, **Employees** data with the following fields:
1. Email
2. Position
3. First Name
4. Last Name

Then when creating the following resource:

```
data "personio_employees" "all" {
}
```

I am getting the this error:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-personio_v0.3.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100b0be98]

goroutine 36 [running]:
github.com/nicoangelo/terraform-provider-personio/internal/adapter.EmployeeProfile.AllNull({{0x0, {0x0, 0x0}}, {0x0, {0x0, 0x0}}, {0x0, 0x0}, {0x0, {0x0, ...}}, ...})
	github.com/nicoangelo/terraform-provider-personio/internal/adapter/employee.go:46 +0x48
github.com/nicoangelo/terraform-provider-personio/internal/adapter.convertProfile(0x0?)
	github.com/nicoangelo/terraform-provider-personio/internal/adapter/employee.go:174 +0x580
github.com/nicoangelo/terraform-provider-personio/internal/adapter.NewEmployee(0x140006921c8)
	github.com/nicoangelo/terraform-provider-personio/internal/adapter/employee.go:114 +0x428
github.com/nicoangelo/terraform-provider-personio/internal/adapter.(*PersonioAdapter).GetEmployees(0x100b50a37?)
	github.com/nicoangelo/terraform-provider-personio/internal/adapter/adapter.go:35 +0xac
github.com/nicoangelo/terraform-provider-personio/internal/provider.(*EmployeesDataSource).Read(0x1400000e060, {0x100f22a40, 0x14000178c90}, {{{{0x100f25d90, 0x14000348ed0}, {0x100e44120, 0x14000348660}}, {0x100f27328, 0x14000694d00}}, {{{0x0, ...}, ...}, ...}}, ...)
	github.com/nicoangelo/terraform-provider-personio/internal/provider/employees_data_source.go:96 +0x174
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0x140002a1080, {0x100f22a40, 0x14000178c90}, 0x14000178d80, 0x140003515e8)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_readdatasource.go:75 +0x39c
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0x140002a1080, {0x100f22a40?, 0x14000178b40?}, 0x1400020a160)
	github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_readdatasource.go:52 +0x1b4
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0x1400015e1e0, {0x100f22a40?, 0x140001781b0?}, 0x1400017a0a0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:656 +0x36c
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x100ef3540?, 0x1400015e1e0}, {0x100f22a40, 0x140001781b0}, 0x1400043e000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:455 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400047c000, {0x100f26490, 0x14000102d00}, 0x1400017c000, 0x1400010e720, 0x101367f90, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xc7c
google.golang.org/grpc.(*Server).handleStream(0x1400047c000, {0x100f26490, 0x14000102d00}, 0x1400017c000, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x298

Error: The terraform-provider-personio_v0.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by nicoangelo** [comment]
Hi @kostyantyn,

Thanks for reporting this issue.

I've never tested it with a very restricted set of attributes. I'll have a look into it during the next days.

**Comment by jbdelpech** [comment]
Hi there,

If it can help, I had to test this module with a restricted token and I crafted a quick and dirty solution by making most of employee attributes optional.

From the tests I made, It looks OK. [Here is the code](https://github.com/jbdelpech/terraform-provider-personio/commit/a52ad05780c05ebab463f2a24f468775d330459f): do not use it, I plan to delete this fork soon.

**Comment by nicoangelo** [comment]
v0.4.0 is being built and should be ready within the next minutes
